"""empty message

Revision ID: 5ae8f95ffbe6
Revises: ebeac3604b8d
Create Date: 2020-03-05 19:46:09.438919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae8f95ffbe6'
down_revision = 'ebeac3604b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_movie_id', sa.Integer(), nullable=True),
    sa.Column('h_hall_id', sa.Integer(), nullable=True),
    sa.Column('h_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['h_hall_id'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['h_movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall_movie')
    # ### end Alembic commands ###
