"""empty message

Revision ID: ebeac3604b8d
Revises: 9685b0955690
Create Date: 2020-03-05 19:22:29.933911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebeac3604b8d'
down_revision = '9685b0955690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_address_id', sa.Integer(), nullable=True),
    sa.Column('h_num', sa.Integer(), nullable=True),
    sa.Column('h_seats', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['h_address_id'], ['cinema_address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall')
    # ### end Alembic commands ###
